Avoid crashing when daemon statistics are inconsistent
During a software upgrade the number of field names for daemon
statistics could be different and when we pull statistics during
that process we die as data structures which are created per socket file
don't contain the same amount of keys.

This is the exception which we receive in that case:

Traceback (most recent call last):
File "/foo/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
self.run()
File "/foo/lib/python3.4/site-packages/haproxystats/process.py", line 150, in run
self.process_stats(incoming_dir)
File "/foo/lib/python3.4/site-packages/haproxystats/utils.py", line 738, in wrapper
result = func(self, *args, **kwargs) haproxystats-process[30013]: File "/foo/lib/python3.4/site-packages/haproxystats/process.py", line 195, in process_stats
self.haproxy_stats(files)
File "/foo/lib/python3.4/site-packages/haproxystats/utils.py", line 738, in wrapper
result = func(self, *args, **kwargs)
File "/foo/lib/python3.4/site-packages/haproxystats/process.py", line 241, in haproxy_stats
dataframe = pandas.DataFrame(raw_info_stats)
File "/foo/lib/python3.4/site-packages/pandas/core/frame.py", line 226, in __init__
mgr = self._init_dict(data, index, columns, dtype=dtype)
File "/foo/lib/python3.4/site-packages/pandas/core/frame.py", line 363, in _init_dict
dtype=dtype)
File "/foo/lib/python3.4/site-packages/pandas/core/frame.py", line 5158, in _arrays_to_mgr
index = extract_index(arrays)
File "/foo/lib/python3.4/site-packages/pandas/core/frame.py", line 5206, in extract_index
raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length