Catch the case when FD is closed from outside
Today I got this trace when local carbon-relay was in bad state

[Consumer-1 ] [_create_connection  ] INFO     connecting to 127.0.0.1 on port 3002
[Consumer-1 ] [open                ] ERROR    failed to connect to 127.0.0.1 on port 3002: timed out
 Process Consumer-1:
 Traceback (most recent call last):
 File "/opt/blue-python/3.4/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
 self.run()
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/process.py", line 139, in run
 self.process_stats(incoming_dir)
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/process.py", line 184, in process_stats
 self.sites_stats(files)
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/process.py", line 273, in sites_stats
 self.process_servers(data_frame)
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/process.py", line 392, in process_servers
 dispatcher.signal('send', data=data)
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/utils.py", line 212, in signal
 handler(**kwargs)
 File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxystats/utils.py", line 297, in send
 self.connection.sendall(bytes(item, 'utf-8'))
 OSError: [Errno 9] Bad file descriptor

I can't find why we receive OSError since we have never opened a
connection. Am I leaking FD?